- name: Install Datadog Agent
  hosts: focalboard
  become: true

  roles:
    - role: datadog.dd.agent

  vars:
    datadog_checks:
      http_check:
        init_config: {}
        instances:
          - name: focalboard-local
            url: "http://127.0.0.1:8000/"
            timeout: 5
